name: password_game
description: Password game completo com Firebase e MVC (login opcional)

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  http: ^1.6.0

  # UtilitÃ¡rios
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/fechado.png
    - assets/images/aberto.png
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"