name: password_game
description: Password game completo com Firebase e MVC (login opcional)

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  http: ^1.6.0

  # UtilitÃ¡rios
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/fechado.png
    - assets/images/aberto.png
    - .env

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icons/logo.png"